# Generated by Django 4.2.7 on 2023-11-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userincome', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'verbose_name_plural': 'Source'},
        ),
        migrations.AddField(
            model_name='userincome',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userincome',
            name='im',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userincome',
            name='nom',
            field=models.TextField(default=''),
        ),
    ]
