# Generated by Django 4.2.7 on 2023-11-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='vendu',
            field=models.IntegerField(default=0),
        ),
    ]
